# Generated by Django 4.2.2 on 2023-06-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='conversion',
            new_name='conversation',
        ),
    ]
